name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "pizzaman12" --password-stdin
        docker build -t cool_docker .
        docker tag cool_docker pizzaman12/nice_docker:latest
        docker push pizzaman12/nice_docker:latest
